version: "3.8"

services:
  app:
    build: ./mobs-api
    container_name: laravel_app
    volumes:
      - ./mobs-api:/var/www/html
    networks:
      - laravel

  web:
    image: nginx:stable-alpine
    container_name: laravel_web
    ports:
      - "8000:80"
    volumes:
      - ./mobs-api:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: postgres:16
    container_name: laravel_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mobs
    ports:
      - "5432:5432"
    networks:
      - laravel
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  laravel:

volumes:
  pgdata:
