# docker-compose.yml
version: "3.8"
services:
  app:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: laravel-app
    restart: unless-stopped
    volumes:
      - ./api:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: >
      sh -c "while ! nc -z db 5432; do sleep 1; done; php artisan serve --host=0.0.0.0 --port=8000"

  db:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  telemetry:
    build:
      context: ./telemetry
      dockerfile: Dockerfile
    image: nestjs-app
    restart: unless-stopped
    volumes:
      - ./telemetry:/usr/src/app
    ports:
      - "3000:3000"

volumes:
  postgres_data:
